import './globals.css'
import { Prompt } from 'next/font/google'
import { Providers } from './providers'

const prompt = Prompt({ subsets: ['thai'], weight: ['400', '600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={prompt.className}>
        <Providers>
          <div className='py-20 max-w-3xl mx-auto w-full px-2'>{children}</div>
        </Providers>
      </body>
    </html>
  )
}
